project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "session1.ipynb"
    - "session2.ipynb"
    - "miniproject/mnist.ipynb"
    - "miniproject/lorenz96.ipynb"
    - "miniproject/shallow_water.ipynb"

website:
  title: "Differentiable Programming"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: session1.ipynb
        text: "Autograd"
      - href: session2.ipynb
        text: "JAX"
      - href: miniproject/mnist.ipynb
        text: "Mini-project with MNIST"
      - href: miniproject/lorenz96.ipynb
        text: "Mini-project with Lorenz '96"
      - href: miniproject/shallow_water.ipynb
        text: "Mini-project with shallow water"

authors: 
  - "Joe Wallwork"
  - "Sam Avis"
  - "Adeleke Bankole"

date-format: "MMMM D, YYYY"
execute:
  enabled: false # need explicit --execute
  error: false
  warning: true
  message: true

jupyter: python3

format:
  html:
    theme: 
      - cosmo
    mainfont: "Source Sans Pro"
    fontsize: 1.1em
    page-layout: article
    linestretch: 1.7
    linkcolor: blue
    smooth-scroll: true
    anchor-sections: true
    citations-hover: true
    footnotes-hover: true
    link-external-newwindow: true
    link-external-icon: true
    toc: true
    toc-depth: 2
    toc-location: left
    number-sections: false
    highlight-style: nord
    code-fold: false
    code-tools: false
    code-line-numbers: false
    code-overflow: scroll
    embed-resources: true
    # grid:
      # sidebar-width: 200px
      # body-width: 900px
      # margin-width: 50px
